const Venue = require('../models/Venue'); const Booking = require('../models/Booking'); const Maintenance = require('../models/Maintenance'); const User = require('../models/User'); const Notification = require('../models/Notification'); const AuditLog = require('../models/AuditLog');
const { conflictForSlot } = require('../utils/bookingHelper');
const { sendBookingUpdate } = require('../utils/mailer');
async function notify(user, message, type = 'info') { return Notification.create({ user, message, type }) }
async function audit(user, action, entity, entityId, details = '') { return AuditLog.create({ user, action, entity, entityId: entityId?.toString(), details }) }

exports.dashboard = async (req, res, next) => {
    try {
        const now = new Date(); const today = new Date(); today.setHours(0, 0, 0, 0); const tomorrow = new Date(today); tomorrow.setDate(tomorrow.getDate() + 1);
        const [venues, bookings, users, pending, todayEvents, revenueAgg, logs] = await Promise.all([
            Venue.find().lean(), Booking.find().populate('venue', 'name').populate('organiser', 'name email').sort({ date: 1 }).lean(), User.countDocuments(), Booking.countDocuments({ status: 'pending' }), Booking.find({ status: 'approved', date: { $gte: today, $lt: tomorrow } }).populate('venue', 'name').populate('organiser', 'name').sort({ startTime: 1 }).lean(), Booking.aggregate([{ $match: { status: { $in: ['approved', 'completed'] } } }, { $group: { _id: null, total: { $sum: '$totalAmount' }, hours: { $sum: '$durationHours' } } }]), AuditLog.find().populate('user', 'name').sort({ createdAt: -1 }).limit(8).lean()
        ]);
        const upcoming = bookings.filter(b => ['approved', 'pending'].includes(b.status) && new Date(b.date) >= today).slice(0, 8);
        const totalRevenue = revenueAgg[0]?.total || 0, totalHours = revenueAgg[0]?.hours || 0;
        const utilisation = venues.map(v => { const hours = bookings.filter(b => b.venue?._id?.toString() === v._id.toString() && ['approved', 'completed'].includes(b.status)).reduce((s, b) => s + b.durationHours, 0); return { ...v, bookedHours: hours, utilisation: Math.min(100, Math.round(hours / Math.max(1, 14 * 30) * 100)) } });
        res.render('admin/dashboard', { title: 'Admin command centre', venues, bookings, users, pending, todayEvents, upcoming, totalRevenue, totalHours, utilisation, logs });
    } catch (e) { next(e) }
};

exports.venues = async (req, res, next) => { try { const venues = await Venue.find().sort({ createdAt: -1 }).lean(); const maintenance = await Maintenance.find().populate('venue', 'name').sort({ date: 1 }).lean(); res.render('admin/venues', { title: 'Manage venues', venues, maintenance }); } catch (e) { next(e) } };
exports.createVenue = async (req, res, next) => { try { const { name, description, location, floor, roomNumber, capacity, hourlyRate, facilities = '', images = '', openingTime = '08:00', closingTime = '22:00' } = req.body; await Venue.create({ name, description, location, floor, roomNumber, capacity: +capacity, hourlyRate: +hourlyRate, facilities: facilities.split(',').map(s => s.trim()).filter(Boolean), images: images.split('\n').map(s => s.trim()).filter(Boolean), openingTime, closingTime }); await audit(req.user, 'CREATE', 'Venue', '', name); res.redirect('/admin/venues'); } catch (e) { next(e) } };
exports.updateVenue = async (req, res, next) => { try { const v = await Venue.findById(req.params.id); if (!v) return res.status(404).send('Not found'); const { name, description, location, floor, roomNumber, capacity, hourlyRate, facilities = '', images = '', openingTime, closingTime, active } = req.body; Object.assign(v, { name, description, location, floor, roomNumber, capacity: +capacity, hourlyRate: +hourlyRate, facilities: facilities.split(',').map(s => s.trim()).filter(Boolean), images: images.split('\n').map(s => s.trim()).filter(Boolean), openingTime, closingTime, active: active === 'on' }); await v.save(); await audit(req.user, 'UPDATE', 'Venue', v._id, name); res.redirect('/admin/venues'); } catch (e) { next(e) } };
exports.deleteVenue = async (req, res, next) => { try { const v = await Venue.findById(req.params.id); if (v) { v.active = false; await v.save(); await audit(req.user, 'ARCHIVE', 'Venue', v._id, v.name) } res.redirect('/admin/venues') } catch (e) { next(e) } };
exports.addMaintenance = async (req, res, next) => { try { const { venueId, date, startTime, endTime, reason } = req.body; if (await conflictForSlot({ venueId, date, startTime, endTime })) return res.status(409).send('That maintenance window overlaps an active booking or maintenance block.'); const m = await Maintenance.create({ venue: venueId, date: new Date(date), startTime, endTime, reason, createdBy: req.user._id }); await audit(req.user, 'BLOCK', 'Maintenance', m._id, reason); res.redirect('/admin/venues') } catch (e) { next(e) } };
exports.deleteMaintenance = async (req, res, next) => { try { await Maintenance.findByIdAndDelete(req.params.id); res.redirect('/admin/venues') } catch (e) { next(e) } };

exports.bookings = async (req, res, next) => { try { const status = req.query.status; const query = status ? { status } : {}; const bookings = await Booking.find(query).populate('venue', 'name capacity').populate('organiser', 'name email').sort({ date: 1, startTime: 1 }).lean(); res.render('admin/bookings', { title: 'Booking approvals', bookings, status: status || 'all' }); } catch (e) { next(e) } };
async function getBooking(id) { return Booking.findById(id).populate('venue', 'name').populate('organiser', 'name email') }
exports.approve = async (req, res, next) => { try { const b = await getBooking(req.params.id); if (!b || b.status !== 'pending') return res.status(400).send('Booking is no longer pending.'); const c = await conflictForSlot({ venueId: b.venue._id, date: b.date, startTime: b.startTime, endTime: b.endTime, excludeId: b._id }); if (c) return res.status(409).send('Cannot approve: the slot now conflicts with another booking or maintenance block.'); b.status = 'approved'; await b.save(); await notify(b.organiser._id, `Your booking for ${b.eventName} at ${b.venue.name} was approved.`, 'success'); await sendBookingUpdate(b.organiser.email, b.organiser.name, 'Evently booking approved', `Your booking for <b>${b.eventName}</b> at <b>${b.venue.name}</b> has been approved.`).catch(() => { }); await audit(req.user, 'APPROVE', 'Booking', b._id, b.eventName); res.redirect('/admin/bookings'); } catch (e) { next(e) } };
exports.reject = async (req, res, next) => { try { const b = await getBooking(req.params.id); if (!b || b.status !== 'pending') return res.status(400).send('Booking is no longer pending.'); b.status = 'rejected'; b.rejectionReason = req.body.reason || 'Rejected by venue manager'; await b.save(); await notify(b.organiser._id, `Your booking for ${b.eventName} was rejected: ${b.rejectionReason}`, 'warning'); await sendBookingUpdate(b.organiser.email, b.organiser.name, 'Evently booking update', `Your booking for <b>${b.eventName}</b> was rejected. Reason: ${b.rejectionReason}`).catch(() => { }); await audit(req.user, 'REJECT', 'Booking', b._id, b.rejectionReason); res.redirect('/admin/bookings'); } catch (e) { next(e) } };
exports.complete = async (req, res, next) => { try { const b = await Booking.findById(req.params.id); if (!b || b.status !== 'approved') return res.status(400).send('Only approved bookings can be completed.'); b.status = 'completed'; await b.save(); await audit(req.user, 'COMPLETE', 'Booking', b._id, b.eventName); res.redirect('/admin/bookings'); } catch (e) { next(e) } };
exports.cancel = async (req, res, next) => { try { const b = await Booking.findById(req.params.id); if (!b) return res.status(404).send('Not found'); b.status = 'cancelled'; b.cancelledReason = req.body.reason || 'Cancelled by admin'; await b.save(); await notify(b.organiser, `Booking ${b.bookingCode} was cancelled by the venue manager.`, 'warning'); await audit(req.user, 'CANCEL', 'Booking', b._id, b.cancelledReason); res.redirect('/admin/bookings'); } catch (e) { next(e) } };
exports.checkin = async (req, res, next) => { try { const b = await Booking.findOne({ bookingCode: req.body.bookingCode }); if (!b || !['approved', 'completed'].includes(b.status)) return res.status(400).json({ ok: false, message: 'Valid approved booking not found.' }); b.checkedIn = true; b.checkedInAt = new Date(); await b.save(); await audit(req.user, 'CHECK_IN', 'Booking', b._id, b.bookingCode); res.json({ ok: true, message: `Check-in confirmed for ${b.eventName}.` }); } catch (e) { next(e) } };
exports.reports = async (req, res, next) => { try { const bookings = await Booking.find({ status: { $in: ['approved', 'completed'] } }).populate('venue', 'name').populate('organiser', 'name').sort({ date: 1 }).lean(); const total = bookings.reduce((s, b) => s + b.totalAmount, 0); res.render('admin/reports', { title: 'Reports & exports', bookings, total }); } catch (e) { next(e) } };
exports.csv = async (req, res, next) => { try { const bs = await Booking.find().populate('venue', 'name').populate('organiser', 'name').sort({ date: 1 }).lean(); const esc = x => `"${String(x ?? '').replace(/"/g, '""')}"`; const rows = [['Booking ID', 'Event', 'Organiser', 'Venue', 'Date', 'Start', 'End', 'Status', 'Amount', 'Checked In'], ...bs.map(b => [b.bookingCode, b.eventName, b.organiser?.name, b.venue?.name, b.date.toISOString().slice(0, 10), b.startTime, b.endTime, b.status, b.totalAmount, b.checkedIn])]; res.type('text/csv').set('Content-Disposition', 'attachment; filename="evently-bookings.csv"').send(rows.map(r => r.map(esc).join(',')).join('\n')); } catch (e) { next(e) } };
