const Booking = require('../models/Booking'); const Venue = require('../models/Venue'); const Notification = require('../models/Notification'); const AuditLog = require('../models/AuditLog');
const { conflictForSlot, validTimes, durationHours, normalizeDate, makeBookingCode } = require('../utils/bookingHelper');
const { suggestAlternatives } = require('../utils/recommendation');
const QRCode = require('qrcode');
const PDFDocument = require('pdfkit');

async function notify(user, message, type = 'info') { await Notification.create({ user, message, type }) }
async function audit(user, action, entity, entityId, details = '') { await AuditLog.create({ user, action, entity, entityId: entityId?.toString(), details }) }

exports.create = async (req, res, next) => {
    try {
        const { venueId, eventName, eventType, description, attendees, date, startTime, endTime, facilitiesRequested = '', recurrence = 'none', recurrenceCount = '1' } = req.body;
        const venue = await Venue.findById(venueId); if (!venue || !venue.active) return res.status(404).send('Venue not found');
        const attendeeCount = +attendees; if (!eventName || !date || !validTimes(startTime, endTime) || attendeeCount < 1 || attendeeCount > venue.capacity) return res.status(400).send('Please enter valid booking details.');
        const d0 = normalizeDate(date); if (d0 < normalizeDate(new Date())) return res.status(400).send('Booking date cannot be in the past.');
        const count = Math.min(Math.max(+recurrenceCount || 1, 1), 12); const dates = []; for (let i = 0; i < count; i++) { const d = new Date(d0); if (recurrence === 'weekly') d.setDate(d.getDate() + i * 7); else if (recurrence === 'daily') d.setDate(d.getDate() + i); else if (i > 0) break; dates.push(d) }
        const conflicts = []; for (const d of dates) { const c = await conflictForSlot({ venueId: venue._id, date: d, startTime, endTime }); if (c) conflicts.push({ date: d, type: c.type, item: c.item }) }
        if (conflicts.length) { const alts = await suggestAlternatives({ venueId, date: d0, startTime, endTime, capacity: attendeeCount, facilities: facilitiesRequested.split(',').filter(Boolean), requestedRate: venue.hourlyRate }); return res.status(409).render('booking-conflict', { title: 'Slot unavailable', venue, form: req.body, conflicts, alternatives: alts }); }
        const group = dates.length > 1 ? `REC-${Date.now()}` : ''; const dh = durationHours(startTime, endTime);
        const docs = dates.map(d => ({ bookingCode: makeBookingCode(), organiser: req.user._id, venue: venue._id, eventName, eventType, description, attendees: attendeeCount, date: d, startTime, endTime, durationHours: dh, hourlyRate: venue.hourlyRate, totalAmount: Math.round(dh * venue.hourlyRate), facilitiesRequested: facilitiesRequested.split(',').filter(Boolean), status: 'pending', recurrenceGroup: group }));
        const created = await Booking.insertMany(docs); await notify(req.user._id, `${created.length > 1 ? created.length + ' booking requests' : 'Booking request'} submitted for ${venue.name}.`, 'success'); res.redirect('/bookings');
    } catch (e) { next(e) }
};

exports.list = async (req, res, next) => { try { const bookings = await Booking.find({ organiser: req.user._id }).populate('venue', 'name location capacity').sort({ date: -1, startTime: -1 }).lean(); res.render('bookings', { title: 'My bookings', bookings }); } catch (e) { next(e) } };
exports.details = async (req, res, next) => { try { const b = await Booking.findOne({ _id: req.params.id, organiser: req.user._id }).populate('venue').populate('organiser', 'name email').lean(); if (!b) return res.status(404).render('errors/error', { title: 'Booking not found', message: 'The booking was not found.' }); const qr = await QRCode.toDataURL(`EVENTLY|${b.bookingCode}|${b.eventName}|${new Date(b.date).toISOString().slice(0, 10)}|${b.startTime}|${b.endTime}`); res.render('booking-details', { title: b.eventName, booking: b, qr }); } catch (e) { next(e) } };
exports.cancel = async (req, res, next) => { try { const b = await Booking.findOne({ _id: req.params.id, organiser: req.user._id }); if (!b) return res.status(404).send('Not found'); if (!['pending', 'approved'].includes(b.status)) return res.status(400).send('This booking cannot be cancelled.'); if (b.status === 'approved' && (new Date(b.date) - new Date()) < 24 * 3600000) return res.status(400).send('Approved bookings can only be cancelled at least 24 hours before the event.'); b.status = 'cancelled'; b.cancelledReason = req.body.reason || 'Cancelled by organiser'; await b.save(); await notify(req.user._id, `Booking ${b.bookingCode} has been cancelled.`, 'warning'); res.redirect('/bookings'); } catch (e) { next(e) } };

exports.pdf = async (req, res, next) => { try { const b = await Booking.findOne({ _id: req.params.id, organiser: req.user._id }).populate('venue').populate('organiser', 'name email').lean(); if (!b) return res.status(404).send('Booking not found'); const doc = new PDFDocument({ size: 'A4', margin: 50 }); res.setHeader('Content-Type', 'application/pdf'); res.setHeader('Content-Disposition', `attachment; filename="${b.bookingCode}.pdf"`); doc.pipe(res); doc.fontSize(11).text('EVENTLY', 50, 50); doc.fontSize(28).text('EVENT PASS', 50, 95); doc.fontSize(24).text(b.eventName, 50, 140); doc.fontSize(11).fillColor('#666').text(b.description || 'Event booking confirmation', 50, 180, { width: 490 }); doc.fillColor('#111'); doc.fontSize(12).text(`Booking ID: ${b.bookingCode}`, 50, 230); doc.text(`Venue: ${b.venue.name}`, 50, 255); doc.text(`Location: ${b.venue.location}`, 50, 280); doc.text(`Date: ${new Date(b.date).toLocaleDateString('en-IN')}`, 50, 305); doc.text(`Time: ${b.startTime} – ${b.endTime}`, 50, 330); doc.text(`Guests: ${b.attendees}`, 50, 355); doc.text(`Estimated amount: INR ${b.totalAmount.toLocaleString('en-IN')}`, 50, 380); doc.roundedRect(50, 430, 495, 105, 12).stroke(); doc.fontSize(14).text(`Status: ${b.status.toUpperCase()}`, 70, 455); doc.fontSize(10).fillColor('#777').text('Present this booking ID or the QR event pass at the venue entrance.', 70, 485, { width: 450 }); doc.fillColor('#111').fontSize(10).text('Generated by Evently • Campus & Community Edition', 50, 760); doc.end(); } catch (e) { next(e) } };
